### ISSUE TITLE
render project specification fields based on metadata hints

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/InitializrWeb#15]
The configuration metadata from InitializrAPI contains a type hint which can be used to render the HTML component in the UI project specification page.

The sample fields referenced below can be viewed at the [Spring Initializr](https://start.spring.io/).

The type hints are:

- text
- single-select
- hierarchical-multi-select

**text**

This hint is for basic freeform text input.  There may be a default value supplied.  A sample field in the Spring Initializr is _Name_.

Example (description field):

```
description:
  type: text
  default: Demo project for Steeltoe
```

**single-select**

This hint is for fields that must have one and only one of a list of items.  There will be a default value supplied.  

A sample field in the Spring Initializr is _Spring Boot_.

Example (Steeltoe release field):

```
steeltoeRelease:
  type: single-select
  default: 2.4.4
  values:
  - id: 2.4.4
  - id: 3.0.0-m2
```

**hierarchical-multi-select**

This hint is for fields that can have zero or one of list of grouped items.  The groupings are purely to to make it easier for a user to see related items.   There may be one or more default values supplied.  The sample field in the Spring Initializr is _Dependencies_.

Example (dependencies field):

```
dependencies:
  type: hierarchical-multi-select
  values:
  - name: Steeltoe
    values:
    - id: actuators
      name: Actuators
      description: add management endpoints
    - id: circuitbreakers
      name: Circuit Breakers
      description: add circuit breakers
  - name: omeThirdParty
    values:
    - id: somedep
      name: Some Dependency
      description: some 3rd party dependency
```
